WARNING:pygls.protocol:Cancel notification for unknown message id "2"
WARNING:pygls.protocol:Cancel notification for unknown message id "7"
ERROR:pygls.protocol:Failed to handle request 11 textDocument/documentHighlight DocumentHighlightParams(text_document=TextDocumentIdentifier(uri='file:///root/text_analysis/code/_NotebookConcat_2d3d6406fe35.py'), position=3:27, work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/root/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/root/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight
    names = jedi_script.get_references(*jedi_lines, scope="file")
  File "/root/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (27) is not in a valid range (0-12) for line 4 ('import torch\n').
WARNING:pygls.protocol:Cancel notification for unknown message id "12"
